# Generated by Django 2.2 on 2021-01-09 06:37

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_url', models.CharField(max_length=40)),
                ('admin_id', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=10)),
                ('auth_write', models.BooleanField(default=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField()),
                ('session_id', models.CharField(max_length=40)),
                ('is_public', models.BooleanField(default=False)),
                ('pen_type', models.IntegerField(choices=[(0, 'pencil'), (1, 'pen'), (2, 'highlight')], default=0)),
                ('color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('data', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Board')),
            ],
        ),
    ]
