# Generated by Django 3.1.5 on 2021-01-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_path_path_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
