# Generated by Django 2.2 on 2021-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_write',
            field=models.BooleanField(default=False),
        ),
    ]
