# Generated by Django 3.1.5 on 2021-01-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210109_1641'),
        ('main', '0004_auto_20210109_1930'),
    ]

    operations = [
    ]
