# Generated by Django 3.1.5 on 2021-01-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20210109_1934'),
        ('main', '0005_auto_20210109_2154'),
    ]

    operations = [
    ]
